version: '3'

services:
  clinica-app:
    container_name: clinica-app
    build: .
    ports:
      - '8000:8000'
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
